schema:
  - '${NEXT_PUBLIC_API_ENDPOINT}/graphql':
      headers:
        x-introspect-secret: '${GRAPHQL_INTROSPECT_SECRET}'
extensions:
  codegen:
    generates:
      ./src/schema/schema.graphql:
        plugins:
          - schema-ast
